services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sesame-prueba-oscar
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
